require("core.plugins.config.colorscheme")
require("core.plugins.config.nvim-tree")
require("core.plugins.config.mason")
require("core.plugins.config.treesitter")
require("core.plugins.config.lsp_config")
require("core.plugins.config.completation")
require("core.plugins.config.statusline")
require("core.plugins.config.dashboard")
